INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('AIO', 'United States Air Force', 300000, 5000);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('AA', 'American Airlines', 100000, 900);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('UA', 'United Airlines', 88000, 800);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('DL', 'Delta Air Lines', 86000, 900);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('WN', 'Southwest Airlines', 60000, 750);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('CO', 'Continental Airlines', 55000, 350);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('NW', 'Northwest Airlines', 40000, 320);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('US', 'US Airways', 32000, 350);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('B6', 'JetBlue Airways', 18000, 270);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('ENY', 'Envoy Air', 15000, 700);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('MQ', 'American Eagle Airlines', 14000, 600);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('OO', 'SkyWest', 14000, 500);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('PI', 'Piedmont Airlines', 10000, 150);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('XE', 'ExpressJet', 9000, 400);
INSERT INTO airlines (airline_id, airline_name, num_employees, num_planes) VALUES ('NK', 'Spirit Airlines', 7500, 150);
