INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('Q5', '40-Mile Air', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('AQ', 'Aloha Airlines', 2000, 25);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('AA', 'American Airlines', 100000, 900);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('G4', 'Allegiant Air', 4000, 100);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('KO', 'Alaska Central Express', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('2Q', 'Air Cargo Carriers', 150, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('AIR', 'Airlift International', 200, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('HP', 'America West Airlines', 20000, 200);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('ZW', 'Air Wisconsin', 1500, 75);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('ALO', 'Allegheny Commuter Airlines', 500, 30);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('RSI', 'Air Sunshine', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('AMT', 'ATA Airlines', 5000, 70);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('JW', 'Arrow Air', 400, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('EV', 'Atlantic Southeast Airlines', 2500, 100);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('MQ', 'American Eagle Airlines', 14000, 600);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('ZA', 'Access Air', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('QH', 'Air Florida', 1500, 30);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('5Y', 'Atlas Air', 3000, 80);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('FL', 'AirTran Airways', 8000, 140);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('CH', 'Bemidji Airlines', 150, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('8E', 'Bering Air', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('9K', 'Cape Air', 1000, 70);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('RP', 'Chautauqua Airlines', 1800, 75);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('DQ', 'Coastal Air', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('9L', 'Colgan Air', 1300, 50);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('OH', 'Comair', 4000, 100);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('C5', 'CommutAir', 900, 30);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('CP', 'Compass Airlines', 1500, 60);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('CO', 'Continental Airlines', 55000, 350);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('COEXP', 'Continental Express', 5000, 200);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('CS', 'Continental Micronesia', 1000, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('CRO', 'Crown Airways', 200, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('DL', 'Delta Air Lines', 86000, 900);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('EZ', 'Evergreen International Airlines', 1000, 30);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('EO', 'Express One International', 300, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('XE', 'ExpressJet', 9000, 400);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('RF', 'Florida West International Airways', 200, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('FP', 'Freedom Air', 100, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('FRL', 'Freedom Airlines', 200, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('F9', 'Frontier Airlines', 5000, 90);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('2F', 'Frontier Flying Service', 300, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('G7', 'GoJet Airlines', 1500, 50);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('ZK', 'Great Lakes Airlines', 600, 30);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('GFT', 'Gulfstream International Airlines', 300, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('H6', 'Hageland Aviation Services', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('HA', 'Hawaiian Airlines', 7000, 60);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('QX', 'Horizon Air', 3000, 60);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('I9', 'Indigo', 2000, 50);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('IS', 'Island Airlines', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('QJ', 'Jet Airways', 300, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('B6', 'JetBlue Airways', 18000, 270);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('M5', 'Kenmore Air', 100, 25);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('YV', 'Mesa Airlines', 3000, 150);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('XJ', 'Mesaba Airlines', 2000, 70);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('JI', 'Midway Airlines', 1500, 50);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('YX', 'Midwest Airlines', 3000, 60);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('1I', 'NetJets', 6000, 650);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('EJ', 'New England Airlines', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('NW', 'Northwest Airlines', 40000, 320);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('OY', 'Omni Air International', 500, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('PSA', 'Pacific Island Aviation', 100, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('LW', 'Pacific Wings', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('KS', 'Peninsula Airways', 700, 30);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('PI', 'Piedmont Airlines (1948-1989)', 10000, 150);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('9E', 'Pinnacle Airlines', 7000, 140);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('BK', 'Potomac Air', 300, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('RW', 'Republic Airlines', 6000, 180);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('RYA', 'Ryan Air Services', 100, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('RD', 'Ryan International Airlines', 500, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('BB', 'Seaborne Airlines', 200, 12);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('SCE', 'Scenic Airlines', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('SY', 'Sun Country Airlines', 1600, 30);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('SEA', 'Southeast Air', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('N5', 'Skagway Air Service', 20, 2);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('WN', 'Southwest Airlines', 60000, 750);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('AL', 'Skywalk Airlines', 100, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('NK', 'Spirit Airlines', 7500, 150);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('OO', 'SkyWest', 14000, 500);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('SOU', 'Southern Airways', 300, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('SPI', 'South Pacific Island Airways', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('S5', 'Shuttle America', 2000, 70);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('AX', 'Trans States Airlines', 1000, 35);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('U5', 'USA3000 Airlines', 600, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('UA', 'United Airlines', 88000, 800);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('US', 'US Airways', 32000, 350);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('USH', 'US Helicopter', 100, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('AIO', 'United States Air Force', 300000, 5000);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('UH', 'US Helicopter Corporation', 100, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('VX', 'Virgin America', 3000, 60);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('WA', 'Western Airlines', 12000, 100);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('WO', 'World Airways', 500, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('KW', 'Carnival Air Lines', 1000, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('WP', 'Island Air (WP)', 300, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('FA', 'Epic Holiday', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('TQ', 'Texas Wings', 200, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('A1', 'Atifly', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('3E', 'Air Choice One', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('ZQ', 'Locair', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('K5', 'SeaPort Airlines', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('S6', 'Salmon Air', 30, 3);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('J5', 'Alaska Seaplane Service', 20, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('6P', 'Gryphon Airlines', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('-+', 'U.S. Air', 32000, 350);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('WQ', 'PanAm World Airways', 500, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('XBM', 'CBM America', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('BZ', 'Black Stallion Airways', 30, 3);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('Y1', 'Yellowstone Club Private Shuttle', 20, 2);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('T6', 'Trans Pas Air', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('HI', 'Papillon Grand Canyon Helicopters', 100, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('E1', 'Usa Sky Cargo', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('7H', 'Era Alaska', 300, 30);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('H1', 'Hankook Air US', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('OBT', 'Orbit Airlines', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('YR', 'SENIC AIRLINES', 20, 2);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('XOJ', 'XOJET', 100, 40);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('OAI', 'Orbit International Airlines', 200, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('OAR', 'Orbit Regional Airlines', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('OAN', 'Orbit Atlantic Airways', 150, 15);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('B0', 'Aws express', 10, 1);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('76', 'Southjet', 500, 50);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('77', 'Southjet connect', 200, 20);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('78', 'Southjet cargo', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('P4', 'Patriot Airways', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('V2', 'Vision Airlines (V2)', 300, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('YE', 'Yellowtail', 20, 2);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('KG', 'Royal Airways', 100, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('XSR', 'Executive AirShare', 200, 50);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('TJ', 'T.J. Air', 10, 2);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('M1', 'Maryland Air', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('ZM', 'Apache Air', 20, 2);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('N8', 'National Air Cargo', 200, 10);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('13', 'Eastern Atlantic Virtual Airlines', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('EVC', 'Comfort Express Virtual Charters Albany', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('CEO', 'Comfort Express Virtual Charters', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('XA', 'XAIR USA', 50, 5);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('ENY', 'Envoy Air', 15000, 700);
INSERT INTO airlines (airline_id, name, num_employess, num_planes) VALUES ('RN', 'Rainbow Air (RAI)', 20, 2);
